Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,17 +1,40 @@
-# .github/workflows/sync.yml
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
-    schedule:
-        - cron: "0 8 * * *" # 每天0点触发
-    workflow_dispatch:
+  schedule:
+    - cron: "0 8 * * *" # every hour
+  workflow_dispatch:
+
 jobs:
-    repo-sync:
-        runs-on: ubuntu-latest
-        steps:
-            - uses: tgymnich/fork-sync@v1.8
-              with:
-                  github_token: ${{ secrets.GITHUB_TOKEN }} # 这个 token action 会默认配置, 这里只需这样写就行
-                  owner: Yidadaa # fork 上游项目 owner
-                  head: main # fork 上游项目需要同步的分支
-                  base: main # 需要同步到本项目的目标分支
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
+    runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
+
+    steps:
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo: Yidadaa/ChatGPT-Next-Web
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
+
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "::error::由于权限不足，导致同步失败（这是预期的行为），请前往仓库首页手动执行[Sync fork]。"
+          echo "::error::Due to insufficient permissions, synchronization failed (as expected). Please go to the repository homepage and manually perform [Sync fork]."
+          exit 1
